### ISSUE TITLE
バグ修正

### ISSUE THREAD

**Issue by kenton116** [kenton116/Favorite-PictureViewer#1]
画像が２列目になった時、コメントが下に下りてしまうバグがあるので修正したい。

**Comment by fuuchin** [comment]
# テストメール
OKですか？

**Comment by kenton116** [comment]
okです

**Comment by fuuchin** [comment]
写真  
写真  
メモメモ  
ではいけないということでしょうか？

**Comment by kenton116** [comment]
そういうことです

**Comment by fuuchin** [comment]
写真写真写真写真  
メモメモメモメモ  
写真写真写真写真  
メモメモメモメモ  
になったらいいんですね！

**Comment by kenton116** [comment]
そうです！

**Comment by fuuchin** [comment]
> 最悪だ、また新バージョンのhtmlが反映されない。＜＜同じく

**Comment by kenton116** [comment]
どうすればいいのでしょうか

**Comment by fuuchin** [comment]
僕たちだけでは解決できないかも  
みんな必死でslack見てないのかも

**Comment by fuuchin** [comment]
> 最悪だ、また新バージョンのhtmlが反映されない。＜＜時間たてばいける

**Comment by kenton116** [comment]
時間経っても無理な時がある（今その状態）

**Comment by kenton116** [comment]
らべねこ先生のヒントで解決しました。ありがとうございました
